from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path

from moth.profiles.loader import load_profile, match_profile
from moth.profiles.scaffold import build_profile_scaffold
from moth.profiles.scaffold import default_profile_path
from moth.profiles.scaffold import parse_complexity_command
from moth.profiles.scaffold import parse_evidence_paths
from moth.profiles.scaffold import write_profile_scaffold
from moth.report import build_affected_report
from moth.report import build_profiles_report
from moth.report import build_sync_report
from moth.report import render_affected_markdown
from moth.report import render_profiles_markdown
from moth.snapshot import build_snapshot, render_json, render_markdown
from moth.schema import SNAPSHOT_SCHEMA_VERSION
from moth.schema import utc_now_iso
from moth.workspace import build_workspace_report
from moth.workspace import render_workspace_markdown


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="moth", description="Cross-repo audit atlas")
    sub = parser.add_subparsers(dest="cmd", required=True)

    snapshot = sub.add_parser("snapshot", help="Emit a machine-readable repo snapshot")
    snapshot.add_argument("--repo", required=True, help="Repo path to inspect")
    snapshot.add_argument("--profile", help="Explicit profile name or YAML path")
    snapshot.add_argument("--format", choices=("markdown", "json"), default="json")
    snapshot.add_argument("--output", help="Optional file path to persist the rendered payload")

    doctor = sub.add_parser("doctor", help="Validate a repo profile and emit a summary")
    doctor.add_argument("--repo", required=True, help="Repo path to inspect")
    doctor.add_argument("--profile", help="Explicit profile name or YAML path")
    doctor.add_argument("--format", choices=("markdown", "json"), default="markdown")
    doctor.add_argument("--output", help="Optional file path to persist the rendered payload")

    report = sub.add_parser("report", help="Render a report for a repo profile")
    report.add_argument("--repo", required=True, help="Repo path to inspect")
    report.add_argument("--profile", help="Explicit profile name or YAML path")
    report.add_argument("--format", choices=("markdown", "json"), default="markdown")
    report.add_argument("--output", help="Optional file path to persist the rendered payload")

    profile_cmd = sub.add_parser("profile", help="Show a profile")
    profile_cmd.add_argument("ref", help="Profile name or YAML path")
    profile_cmd.add_argument("--format", choices=("markdown", "json"), default="json")
    profile_cmd.add_argument("--output", help="Optional file path to persist the rendered payload")

    profiles_cmd = sub.add_parser("profiles", help="List available profiles")
    profiles_cmd.add_argument("--workspace", help="Workspace root to discover repo-local profiles")
    profiles_cmd.add_argument("--format", choices=("markdown", "json"), default="json")
    profiles_cmd.add_argument("--output", help="Optional file path to persist the rendered payload")

    assert_cmd = sub.add_parser("assert", help="Run only the profile's assertion packs (fast path)")
    assert_cmd.add_argument("--repo", required=True, help="Repo path to inspect")
    assert_cmd.add_argument("--profile", help="Explicit profile name or YAML path")
    assert_cmd.add_argument("--format", choices=("markdown", "json"), default="markdown")

    coupling_cmd = sub.add_parser("coupling", help="Coupling/orphan-ref check: --impact <name> 看删前 fan-in, 或扫孤儿引用")
    coupling_cmd.add_argument("--repo", required=True, help="Repo path to inspect")
    coupling_cmd.add_argument("--impact", metavar="NAME", help="删 NAME (表名/文件名/标识符) 前看全 fan-in 爆炸半径")
    coupling_cmd.add_argument("--format", choices=("markdown", "json"), default="markdown")

    workspace_cmd = sub.add_parser("workspace", help="Inspect all repo-local profiles in a workspace")
    workspace_cmd.add_argument("--workspace", required=True, help="Workspace root to inspect")
    workspace_cmd.add_argument("--format", choices=("markdown", "json"), default="json")
    workspace_cmd.add_argument("--output", help="Optional file path to persist the rendered payload")

    init_cmd = sub.add_parser("init", help="Create a repo-local moth profile scaffold")
    init_cmd.add_argument("--repo", required=True, help="Repo path to scaffold")
    init_cmd.add_argument("--name", help="Profile name to write")
    init_cmd.add_argument("--output", help="Output profile path (defaults to <repo>/.moth/profile.yaml)")
    init_cmd.add_argument(
        "--complexity-command",
        help="Shell-style complexity command to store in the scaffold",
    )
    init_cmd.add_argument(
        "--evidence-path",
        action="append",
        default=[],
        help="Evidence path in label=path form; may be repeated",
    )
    init_cmd.add_argument("--notes", default="Generated by moth init.", help="Profile notes")
    init_cmd.add_argument("--force", action="store_true", help="Overwrite an existing profile")
    init_cmd.add_argument("--format", choices=("markdown", "json"), default="json")

    sync_cmd = sub.add_parser("sync", help="Refresh CodeGraph and emit the latest snapshot")
    sync_cmd.add_argument("--repo", required=True, help="Repo path to inspect")
    sync_cmd.add_argument("--profile", help="Explicit profile name or YAML path")
    sync_cmd.add_argument("--format", choices=("markdown", "json"), default="json")
    sync_cmd.add_argument("--output", help="Optional file path to persist the rendered payload")

    affected_cmd = sub.add_parser("affected", help="Map changed files to affected tests and scoped complexity findings")
    affected_cmd.add_argument("--repo", required=True, help="Repo path to inspect")
    affected_cmd.add_argument("--profile", help="Explicit profile name or YAML path")
    affected_cmd.add_argument("--file", action="append", default=[], help="Changed file path; may be repeated")
    affected_cmd.add_argument("files", nargs="*", help="Changed file paths")
    affected_cmd.add_argument("--depth", type=int, default=5, help="CodeGraph dependency traversal depth")
    affected_cmd.add_argument("--test-filter", help="CodeGraph affected test glob filter")
    affected_cmd.add_argument("--format", choices=("markdown", "json"), default="json")
    affected_cmd.add_argument("--output", help="Optional file path to persist the rendered payload")

    return parser


def _resolve_profile(repo: str, profile_ref: str | None):
    if profile_ref:
        return load_profile(profile_ref)
    matched = match_profile(repo)
    if matched is None:
        raise SystemExit(f"no profile matched repo {repo!r}; pass --profile explicitly")
    return matched


def _render_mapping_block(mapping: dict[str, object]) -> list[str]:
    return [f"  - {sub_key}: `{sub_value}`" for sub_key, sub_value in mapping.items()]


def _write_output(output_path: str | None, rendered: str) -> None:
    if not output_path:
        return
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rendered, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    if args.cmd == "assert":
        from moth.checks.assertions import run_assertion_packs

        profile = _resolve_profile(args.repo, args.profile)
        outcome = run_assertion_packs(profile.assertion_packs, profile.repo_path)
        if args.format == "json":
            sys.stdout.write(render_json(outcome) + "\n")
        else:
            totals = outcome["totals"]
            sys.stdout.write(
                f"verdict={outcome['verdict']} pass={totals['pass']}"
                f" fail={totals['fail']} error={totals['error']}\n"
            )
            for pack in outcome["packs"]:
                for r in pack["results"]:
                    if r["status"] != "pass":
                        sys.stdout.write(
                            f"[{r['status'].upper()}] {r['id']}: observed={r['observed']!r}"
                            + (f" | {r['detail']}" if r["detail"] else "") + "\n"
                        )
            for issue in outcome["issues"]:
                sys.stdout.write(f"[ISSUE] {issue}\n")
        return 0 if outcome["verdict"] != "FAIL" else 1

    if args.cmd == "coupling":
        from moth.checks.coupling import impact, orphans, render_impact, render_orphans

        repo = Path(args.repo).resolve()
        if args.impact:
            result = impact(repo, args.impact)
            sys.stdout.write(render_json(result) + "\n" if args.format == "json" else render_impact(result))
            return 0
        result = orphans(repo)
        sys.stdout.write(render_json(result) + "\n" if args.format == "json" else render_orphans(result))
        return 0 if result["verdict"] != "FAIL" else 1

    if args.cmd in {"doctor", "report", "snapshot"}:
        profile = _resolve_profile(args.repo, args.profile)
        payload = build_snapshot(profile)
        rendered = render_json(payload) + "\n" if args.format == "json" else render_markdown(payload)
        _write_output(args.output, rendered)
        sys.stdout.write(rendered)
        return 0 if payload["status"] != "FAIL" else 1

    if args.cmd == "profile":
        profile = load_profile(args.ref)
        payload = {
            "kind": profile.kind,
            "name": profile.name,
            "repo_path": str(profile.repo_path),
            "codegraph_root": str(profile.codegraph_root),
            "complexity_command": profile.complexity_command,
            "complexity_baseline_path": str(profile.complexity_baseline_path) if profile.complexity_baseline_path else None,
            "evidence_paths": {label: str(path) for label, path in profile.evidence_paths.items()},
            "instruction_sources": profile.instruction_sources,
            "notes": profile.notes,
        }
        if args.format == "markdown":
            rendered = "# Moth profile\n\n"
            for key, value in payload.items():
                if isinstance(value, dict):
                    rendered += f"- {key}:\n"
                    rendered += "\n".join(_render_mapping_block(value)) + "\n"
                else:
                    rendered += f"- {key}: `{value}`\n"
        else:
            rendered = render_json(payload) + "\n"
        _write_output(args.output, rendered)
        if args.format == "markdown":
            sys.stdout.write(rendered)
        else:
            sys.stdout.write(rendered)
        return 0

    if args.cmd == "profiles":
        payload = build_profiles_report(args.workspace)
        rendered = render_json(payload) + "\n" if args.format == "json" else render_profiles_markdown(payload)
        _write_output(args.output, rendered)
        sys.stdout.write(rendered)
        return 0 if payload["status"] != "FAIL" else 1

    if args.cmd == "workspace":
        payload = build_workspace_report(args.workspace)
        rendered = render_json(payload) + "\n" if args.format == "json" else render_workspace_markdown(payload)
        _write_output(args.output, rendered)
        sys.stdout.write(rendered)
        return 0 if payload["status"] != "FAIL" else 1

    if args.cmd == "init":
        repo_path = args.repo
        output = args.output or str(default_profile_path(repo_path))
        payload = build_profile_scaffold(
            repo_path,
            name=args.name,
            complexity_command=parse_complexity_command(args.complexity_command),
            evidence_paths=parse_evidence_paths(args.evidence_path),
            notes=args.notes,
        )
        try:
            written = write_profile_scaffold(output, payload, force=args.force)
        except Exception as exc:
            result = {
                "schema_version": SNAPSHOT_SCHEMA_VERSION,
                "generated_at": utc_now_iso(),
                "status": "FAIL",
                "output_path": str(output),
                "profile": payload,
                "issues": [str(exc)],
                "warnings": [],
            }
            if args.format == "json":
                sys.stdout.write(render_json(result) + "\n")
            else:
                sys.stdout.write("# Moth init\n\n")
                sys.stdout.write(f"- Status: `FAIL`\n")
                sys.stdout.write(f"- Output path: `{output}`\n")
                sys.stdout.write("\n## Issues\n")
                sys.stdout.write(f"- {exc}\n")
            return 1
        result = {
            "schema_version": SNAPSHOT_SCHEMA_VERSION,
            "generated_at": utc_now_iso(),
            "status": "PASS",
            "output_path": str(written),
            "profile": payload,
            "issues": [],
            "warnings": [],
        }
        if args.format == "json":
            sys.stdout.write(render_json(result) + "\n")
        else:
            sys.stdout.write("# Moth init\n\n")
            sys.stdout.write(f"- Status: `PASS`\n")
            sys.stdout.write(f"- Output path: `{written}`\n")
            sys.stdout.write(f"- Profile: `{payload['name']}`\n")
            if payload.get("complexity_command"):
                sys.stdout.write(f"- Complexity command: `{shlex.join(payload['complexity_command'])}`\n")
            if payload.get("evidence_paths"):
                sys.stdout.write("\n## Evidence paths\n")
                for label, rel_path in payload["evidence_paths"].items():
                    sys.stdout.write(f"- {label}: `{rel_path}`\n")
        return 0

    if args.cmd == "sync":
        profile = _resolve_profile(args.repo, args.profile)
        payload = build_sync_report(profile)
        if args.format == "json":
            rendered = render_json(payload) + "\n"
        else:
            rendered = "# Moth sync\n\n"
            rendered += f"- Schema version: `{payload['schema_version']}`\n"
            rendered += f"- Generated at: `{payload['generated_at']}`\n"
            rendered += f"- Status: `{payload['status']}`\n"
            rendered += f"- Repo: `{payload['profile']['repo_path']}`\n"
            rendered += f"- CodeGraph sync: `{payload['sync']['verdict']}`\n"
            if payload.get("issues"):
                rendered += "\n## Issues\n"
                for item in payload["issues"]:
                    rendered += f"- {item}\n"
            if payload.get("warnings"):
                rendered += "\n## Warnings\n"
                for item in payload["warnings"]:
                    rendered += f"- {item}\n"
            rendered += "\n## Snapshot\n"
            rendered += render_markdown(payload["snapshot"])
        _write_output(args.output, rendered)
        sys.stdout.write(rendered)
        return 0 if payload["status"] != "FAIL" else 1

    if args.cmd == "affected":
        profile = _resolve_profile(args.repo, args.profile)
        files = [*args.file, *args.files]
        payload = build_affected_report(profile, files, depth=args.depth, test_filter=args.test_filter)
        rendered = render_json(payload) + "\n" if args.format == "json" else render_affected_markdown(payload)
        _write_output(args.output, rendered)
        sys.stdout.write(rendered)
        return 0 if payload["status"] != "FAIL" else 1

    return 2


if __name__ == "__main__":
    raise SystemExit(main())
