from __future__ import annotations

import shlex
from pathlib import Path
from typing import Any

import yaml


def default_profile_path(repo_path: str | Path) -> Path:
    return Path(repo_path).resolve() / ".moth" / "profile.yaml"


def parse_complexity_command(value: str | None) -> list[str]:
    if not value:
        return []
    return shlex.split(value)


def parse_evidence_paths(items: list[str] | None) -> dict[str, str]:
    result: dict[str, str] = {}
    for item in items or []:
        if "=" not in item:
            raise ValueError(f"evidence path must be label=path, got {item!r}")
        label, raw_path = item.split("=", 1)
        label = label.strip()
        raw_path = raw_path.strip()
        if not label or not raw_path:
            raise ValueError(f"evidence path must be label=path, got {item!r}")
        result[label] = raw_path
    return result


def build_profile_scaffold(
    repo_path: str | Path,
    *,
    name: str | None = None,
    complexity_command: list[str] | None = None,
    evidence_paths: dict[str, str] | None = None,
    notes: str = "",
) -> dict[str, Any]:
    repo = Path(repo_path).resolve()
    return {
        "kind": "profile",
        "name": name or repo.name,
        "repo_path": str(repo),
        "codegraph_root": ".",
        "complexity_command": list(complexity_command or []),
        "evidence_paths": dict(evidence_paths or {}),
        "notes": notes or "Generated by moth init.",
    }


def write_profile_scaffold(
    output_path: str | Path,
    payload: dict[str, Any],
    *,
    force: bool = False,
) -> Path:
    path = Path(output_path)
    if path.exists() and not force:
        raise FileExistsError(f"profile already exists: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8")
    return path
